name : issue-workflow
on:
  issues :
    types : [ opened ]
jobs :
  issue-job :
    runs-on : ubuntu-latest
    steps :
      - name : step 1
        run : echo "This is issue workflow"
      - name : step 2
        run : |
          echo "This is issue workflow - step 2"
          echo "Running multiple commands"