name : checkout
on : workflow_dispatch

jobs: 
  no-checkout-job :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout repository
        run : cat README.md

  checkout-job :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout repository
        uses : actions/checkout@v4
      - name : Verify checkout
        run : cat README.md

  context:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: echo '${{ toJson(github) }}' 


  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "Checkout workflow executed successfully!"
            }

