name: Workflow Env Example
on: workflow_dispatch
# env:
#   APP_NAME: MyApp
#   DEPLOY_ENV: production
#   GREETING: "Hello from workflow-level env!"

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print all environment variables
        run: |
          echo "App Name: $APP_NAME"
          echo "Deploy Environment:" ${{ env.APP_NAME }}
          echo "Message: $GREETING"
